version: "3.1"
services:

 db.postgres:
        image: postgres:10
        container_name: db.postgres
        environment:
          - POSTGRES_USER=coaas
          - POSTGRES_PASSWORD=PostCoaaS2017
          - POSTGRES_DB=coaas_auth
        ports:
          - '5432:5432'
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./pgdata:/var/lib/postgresql/data
 mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=alex 
          - MONGODB_PASS=contextstorage_17
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
 mongo-seed:
        build: ./mongo-seed
        restart: on-failure
        depends_on: 
          - mongodb
        links:
          - mongodb

 zookeeper:
        image: wurstmeister/zookeeper
        container_name: "zk"
        ports:
          - "2181:2181"
 kafka:
        image: wurstmeister/kafka
        container_name: "kafka"
        ports:
          - "9092:9092"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zk:2181
          KAFKA_CREATE_TOPICS: "event:3:1"
          HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
        links:
          - zookeeper:zk
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock


 coaas:
   image: ahas36/coaas
   environment:
     - KAFKA_BROKER=kafka:9092
     - MONGO_DB=mongodb:27017
   ports:
     - "8080:8080"
     - "4848:4848"
     - "8181:8181"
     - "9009:9009"
   links:
     - kafka:kafka
     - mongodb:mongodb